/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as MilestonesIndexRouteImport } from './routes/milestones.index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as PatternsSlugRouteImport } from './routes/patterns.$slug'
import { Route as MilestonesMilestoneIdRouteImport } from './routes/milestones.$milestoneId'
import { Route as DesignsSlugRouteImport } from './routes/designs.$slug'
import { Route as ArtifactsSlugRouteImport } from './routes/artifacts.$slug'
import { Route as ApiWatchRouteImport } from './routes/api/watch'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth/github/callback'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsRoute,
} as any)
const MilestonesIndexRoute = MilestonesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MilestonesRoute,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignsRoute,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReportsRoute,
} as any)
const PatternsSlugRoute = PatternsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PatternsRoute,
} as any)
const MilestonesMilestoneIdRoute = MilestonesMilestoneIdRouteImport.update({
  id: '/$milestoneId',
  path: '/$milestoneId',
  getParentRoute: () => MilestonesRoute,
} as any)
const DesignsSlugRoute = DesignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DesignsRoute,
} as any)
const ArtifactsSlugRoute = ArtifactsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ApiWatchRoute = ApiWatchRouteImport.update({
  id: '/api/watch',
  path: '/api/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/designs': typeof DesignsRouteWithChildren
  '/github': typeof GithubRoute
  '/milestones': typeof MilestonesRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/watch': typeof ApiWatchRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/milestones/$milestoneId': typeof MilestonesMilestoneIdRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/milestones/': typeof MilestonesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/github': typeof GithubRoute
  '/search': typeof SearchRoute
  '/api/watch': typeof ApiWatchRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/milestones/$milestoneId': typeof MilestonesMilestoneIdRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/designs': typeof DesignsIndexRoute
  '/milestones': typeof MilestonesIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/designs': typeof DesignsRouteWithChildren
  '/github': typeof GithubRoute
  '/milestones': typeof MilestonesRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/watch': typeof ApiWatchRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/milestones/$milestoneId': typeof MilestonesMilestoneIdRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/milestones/': typeof MilestonesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/artifacts'
    | '/designs'
    | '/github'
    | '/milestones'
    | '/patterns'
    | '/reports'
    | '/search'
    | '/tasks'
    | '/api/watch'
    | '/artifacts/$slug'
    | '/designs/$slug'
    | '/milestones/$milestoneId'
    | '/patterns/$slug'
    | '/reports/$slug'
    | '/tasks/$taskId'
    | '/artifacts/'
    | '/designs/'
    | '/milestones/'
    | '/patterns/'
    | '/reports/'
    | '/tasks/'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/github'
    | '/search'
    | '/api/watch'
    | '/artifacts/$slug'
    | '/designs/$slug'
    | '/milestones/$milestoneId'
    | '/patterns/$slug'
    | '/reports/$slug'
    | '/tasks/$taskId'
    | '/artifacts'
    | '/designs'
    | '/milestones'
    | '/patterns'
    | '/reports'
    | '/tasks'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/artifacts'
    | '/designs'
    | '/github'
    | '/milestones'
    | '/patterns'
    | '/reports'
    | '/search'
    | '/tasks'
    | '/api/watch'
    | '/artifacts/$slug'
    | '/designs/$slug'
    | '/milestones/$milestoneId'
    | '/patterns/$slug'
    | '/reports/$slug'
    | '/tasks/$taskId'
    | '/artifacts/'
    | '/designs/'
    | '/milestones/'
    | '/patterns/'
    | '/reports/'
    | '/tasks/'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  DesignsRoute: typeof DesignsRouteWithChildren
  GithubRoute: typeof GithubRoute
  MilestonesRoute: typeof MilestonesRouteWithChildren
  PatternsRoute: typeof PatternsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SearchRoute: typeof SearchRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiWatchRoute: typeof ApiWatchRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/milestones/': {
      id: '/milestones/'
      path: '/'
      fullPath: '/milestones/'
      preLoaderRoute: typeof MilestonesIndexRouteImport
      parentRoute: typeof MilestonesRoute
    }
    '/designs/': {
      id: '/designs/'
      path: '/'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof DesignsRoute
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/patterns/$slug': {
      id: '/patterns/$slug'
      path: '/$slug'
      fullPath: '/patterns/$slug'
      preLoaderRoute: typeof PatternsSlugRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/milestones/$milestoneId': {
      id: '/milestones/$milestoneId'
      path: '/$milestoneId'
      fullPath: '/milestones/$milestoneId'
      preLoaderRoute: typeof MilestonesMilestoneIdRouteImport
      parentRoute: typeof MilestonesRoute
    }
    '/designs/$slug': {
      id: '/designs/$slug'
      path: '/$slug'
      fullPath: '/designs/$slug'
      preLoaderRoute: typeof DesignsSlugRouteImport
      parentRoute: typeof DesignsRoute
    }
    '/artifacts/$slug': {
      id: '/artifacts/$slug'
      path: '/$slug'
      fullPath: '/artifacts/$slug'
      preLoaderRoute: typeof ArtifactsSlugRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/api/watch': {
      id: '/api/watch'
      path: '/api/watch'
      fullPath: '/api/watch'
      preLoaderRoute: typeof ApiWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsSlugRoute: typeof ArtifactsSlugRoute
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsSlugRoute: ArtifactsSlugRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface DesignsRouteChildren {
  DesignsSlugRoute: typeof DesignsSlugRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
}

const DesignsRouteChildren: DesignsRouteChildren = {
  DesignsSlugRoute: DesignsSlugRoute,
  DesignsIndexRoute: DesignsIndexRoute,
}

const DesignsRouteWithChildren =
  DesignsRoute._addFileChildren(DesignsRouteChildren)

interface MilestonesRouteChildren {
  MilestonesMilestoneIdRoute: typeof MilestonesMilestoneIdRoute
  MilestonesIndexRoute: typeof MilestonesIndexRoute
}

const MilestonesRouteChildren: MilestonesRouteChildren = {
  MilestonesMilestoneIdRoute: MilestonesMilestoneIdRoute,
  MilestonesIndexRoute: MilestonesIndexRoute,
}

const MilestonesRouteWithChildren = MilestonesRoute._addFileChildren(
  MilestonesRouteChildren,
)

interface PatternsRouteChildren {
  PatternsSlugRoute: typeof PatternsSlugRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsSlugRoute: PatternsSlugRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsSlugRoute: typeof ReportsSlugRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSlugRoute: ReportsSlugRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  DesignsRoute: DesignsRouteWithChildren,
  GithubRoute: GithubRoute,
  MilestonesRoute: MilestonesRouteWithChildren,
  PatternsRoute: PatternsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SearchRoute: SearchRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiWatchRoute: ApiWatchRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
